# describes how each step in your analysis should be run

version: '3.0'

expectations:
  population_size: 1000

actions:

    combine_codelists:
        run: r:latest analysis/combine_codelists.R
        outputs:
            highly_sensitive:
                cmd: 'codelists/ons-cmd-codes.csv'
                smi: 'codelists/ons-smi-codes.csv'
                self_harm : 'codelists/ons-self-harm-codes.csv'
                
    generate_cis_visit_level:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_cis_wide --with-end-date-fix
        needs : [combine_codelists]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_wide.csv
    
    transform_cis_wide_to_long:
        run: r:latest analysis/cis_wide_to_long.R
        needs: [generate_cis_visit_level]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_long.csv
    
    reconcile_snomed_ctv3:
        run: r:latest analysis/reconcile_snomed_ctv3.R
        needs: [transform_cis_wide_to_long]
        outputs:
            highly_sensitive:
                cohort: output/input_reconciled.csv
    
    derive_exposed:
        run: r:latest analysis/exposed_population.R
        needs: [reconcile_snomed_ctv3]
        outputs:
            highly_sensitive:
                cohort: output/cis_exposed.csv
    
    derive_controls:
        run: r:latest analysis/control_population.R
        needs: [reconcile_snomed_ctv3]
        outputs:
            highly_sensitive:
                cohort: output/cis_control.csv
                
    perform_matching:
        run: r:latest analysis/create_controls.R
        needs: [derive_exposed, derive_controls]
        outputs:
            highly_sensitive:
                cohort: output/matched_groups.csv
    
    adjust_matched_groups:
        run: r:latest analysis/adjust_groups.R
        needs: [perform_matching]
        outputs:
            highly_sensitive:
                incidence: output/incidence_group.csv
                prevalence: output/prevalence_group.csv
                exacerbated: output/exacerbated_group.csv
    
    descriptive_stats:
        run: r:latest analysis/descriptive_statistics.R
        needs: [adjust_matched_groups]
        outputs:
            moderately_sensitive:
                incidence_cat_stats: output/incidence_cat_stats.csv
                incidence_con_stats: output/incidence_con_stats.csv
                prevalence_cat_stats: output/prevalence_cat_stats.csv
                prevalence_con_stats: output/prevalence_con_stats.csv
                exacerbated_cat_stats: output/exacerbated_cat_stats.csv
                exacerbated_con_stats: output/exacerbated_con_stats.csv
    
    cumulative_incidence:
        run: r:latest analysis/cumulative_incidence_curves.R
        needs: [adjust_matched_groups]
        outputs:
            moderately_sensitive:
                placeholder: output/placeholder.csv
    


