# describes how each step in your analysis should be run

version: '3.0'

expectations:
  population_size: 200

actions:

    combine_codelists:
        run: r:latest analysis/combine_codelists.R
        outputs:
            highly_sensitive:
                cmd: 'codelists/ons-cmd-codes.csv'
                smi: 'codelists/ons-smi-codes.csv'
                self_harm : 'codelists/ons-self-harm-codes.csv'
                
    generate_cis_visit_level:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_cis_wide --with-end-date-fix
        needs: [combine_codelists]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_wide.csv
    
    # generate_cmd_counts:
    #     run: cohortextractor:latest generate_cohort --study-definition study_definition_cmd --with-end-date-fix
    #     needs: [combine_codelists]
    #     outputs:
    #         highly_sensitive:
    #             cohort: output/input_cmd.csv
    
    # population_cmd:
    #     run: r:latest analysis/population_cmd.R
    #     needs: [generate_cmd_counts]
    #     outputs:
    #         highly_sensitive:
    #             cohort: output/population_cmd.csv
    
    transform_cis_wide_to_long:
        run: r:latest analysis/cis_wide_to_long.R
        needs: [generate_cis_visit_level]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_long.csv
    
    reconcile_snomed_ctv3:
        run: r:latest analysis/reconcile_snomed_ctv3.R
        needs: [transform_cis_wide_to_long]
        outputs:
            highly_sensitive:
                cohort: output/input_reconciled.csv
    
    derive_exposed:
        run: r:latest analysis/exposed_population.R
        needs: [reconcile_snomed_ctv3]
        outputs:
            highly_sensitive:
                cohort: output/cis_exposed.csv
    
    derive_controls:
        run: r:latest analysis/control_population.R
        needs: [reconcile_snomed_ctv3]
        outputs:
            highly_sensitive:
                cohort: output/cis_control.csv
                
    perform_matching:
        run: r:latest analysis/create_controls.R
        needs: [derive_exposed, derive_controls]
        outputs:
            highly_sensitive:
                incidence: output/incidence_group.csv
                prevalence: output/prevalence_group.csv
                exacerbated: output/exacerbated_group.csv
    
    adjust_matched_groups:
        run: r:latest analysis/adjust_groups.R
        needs: [perform_matching]
        outputs:
            highly_sensitive:
                incidence: output/adjusted_incidence_group.csv
                prevalence: output/adjusted_prevalence_group.csv
    
    descriptive_stats:
        run: r:latest analysis/descriptive_statistics.R
        needs: [adjust_matched_groups]
        outputs:
            moderately_sensitive:
                incidence_cat_stats: output/incidence_cat_stats.csv
                incidence_con_stats: output/incidence_con_stats.csv
                prevalence_cat_stats: output/prevalence_cat_stats.csv
                prevalence_con_stats: output/prevalence_con_stats.csv
    
    cumulative_incidence:
        run: r:latest analysis/cumulative_incidence_curves.R
        needs: [adjust_matched_groups]
        outputs:
            highly_sensitive:
                inc_t: output/incidence_t.csv
                prev_t: output/prevalence_t.csv
            moderately_sensitive:
                inc_surv: output/incidence_surv.jpg
                prev_surv: output/prevalence_surv.jpg
    


