# describes how each step in your analysis should be run

version: '3.0'

expectations:
  population_size: 1000

actions:
    generate_study_population:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_cis_wide
        outputs:
            highly_sensitive:
                cohort: output/input_cis_wide.csv

    # run: cohortextractor:latest generate_cohort --study-definition study_definition
    #   outputs:
    #     highly_sensitive:
    #       cohort: output/input.csv
    
    transform_cis_wide_to_long:
        run: r:latest analysis/cis_wide_to_long.R
        needs: [generate_study_population]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_long.csv

