# describes how each step in your analysis should be run

version: '3.0'

expectations:
  population_size: 1000

actions:
    generate_cis_visit_level:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_cis_wide
        outputs:
            highly_sensitive:
                cohort: output/input_cis_wide.csv
    
    transform_cis_wide_to_long:
        run: r:latest analysis/cis_wide_to_long.R
        needs: [generate_cis_visit_level]
        outputs:
            highly_sensitive:
                cohort: output/input_cis_long.csv
    
    reconcile_snomed_ctv3:
        run: r:latest analysis/reconcile_snomed_ctv3.R
        needs: [transform_cis_wide_to_long]
        outputs:
            highly_sensitive:
                cohort: output/input_reconciled.csv
    


